# Generated by Django 2.2.12 on 2020-05-16 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pubrish_date',
            new_name='published_date',
        ),
    ]
